spring:
  #mysql数据库连接信息
  datasource:
    #高版本mysql驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #使用com.mysql.cj.jdbc.Driver驱动需要带上时区serverTimezone
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  #jpa相关配置
  jpa:
    database: mysql
    #控制台是否显示sql语句，true：显示 false：不显示
    show-sql: true
    #是否根据实体类（@Entity注解的类）自动建表，true：是 false：否，默认为false
    generate-ddl: true
    hibernate:
      #自动创建或更新或验证数据库表结构，省略不会自动建表
      #create：每次加载Hibernate时都会删除上一次生成的表，然后根据Entity类再重新来生成新表，即使两次没有任何改变也要这样执行，这就是导致数据库表数据丢失的一个重要原因
      #create-drop：每次加载Hibernate时根据Entity类生成表，但是sessionFactory一关闭，表就自动删除
      #update：最常用的属性，第一次加载Hibernate时根据Entity类会自动建立起表的结构（前提是先建立好数据库），以后加载Hibernate时根据Entity类自动更新表结构，
      #即使表结构改变了，但表中的行仍然存在，不会删除以前的行。要注意的是当部署到服务器后，表结构是不会被马上建立起来的，是要等应用第一次运行起来后才会
      #validate：每次加载Hibernate时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值
      ddl-auto: update
    #设置数据库存储引擎为InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect