spring:
  # 配置数据源
  datasource:
    # 数据源类型，使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库驱动，这里配置高版本mysql驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis_plus_test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root

# MyBatis-Plus配置
mybatis-plus:
  #  # MyBatis配置文件位置
  #  config-location: classpath:mybatis/mybatis-config.xml
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:mybatis/mapper/*.xml
  # MyBaits别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.rtxtitanv.model
  global-config:
    db-config:
      #      # 全局逻辑删除的实体字段名
      #      logic-delete-field: deleted
      # 逻辑已删除值，默认为1
      logic-delete-value: 1
      # 逻辑未删除值，默认为0
      logic-not-delete-value: 0
  # 大都为MyBatis原生支持的配置，可以通过MyBatis XML配置文件的形式进行配置
  configuration:
    # 将sql及结果输出到日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    # 是否开启自动驼峰命名规则映射，MyBatis-Plus中默认值为true，MyBatis中原默认值为false
#    map-underscore-to-camel-case: false

## 输出sql日志，com.rtxtitanv.mapper为mapper接口所在包路径
#logging:
#  level:
#    com:
#      rtxtitanv:
#        mapper: debug